services:
  - type: web
    name: churn-demo
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        value: https://churn-demo.onrender.com
    healthCheckPath: /
    autoDeploy: true
